/* eslint-env browser */

'use strict';

var _ = require('object-iterators');

var images = require('../../images/images'); // generated by gulp; ignored by git

_(images).each(function(image, key) {
    var img = new Image();
    img.src = 'data:' + image.type + ';base64,' + image.data;
    images[key] = img;
});

module.exports = images;
