/* eslint-env browser */

'use strict';

var _ = require('object-iterators');

var images = require('../../images'); // this index.js is generated by gulp and ignored by git

_(images).each(function(image, key) {
    var element = new Image();
    element.src = 'data:' + image.type + ';base64,' + image.data;
    images[key] = element;
});

module.exports = images;
